### Kõigi matkade andmete lugemine
GET http://localhost:3030/api/matkad

## Kõigi sõnumite lugemine
GET http://localhost:3030/api/sonumid

### Sõnumi saatmine
POST http://localhost:3030/api/sonumid
Content-Type: application/json

{
    "nimi": "Piplota",
    "sonum": "veel üks sõnum"
}

### Matka loomine
POST http://localhost:3030/api/matk
Content-Type: application/json

{
    "nimetus": "Retk Kõrvemaal",
    "kirjeldus": "palju sõudmist"
}


### 
POST http://localhost:3030/api/todo
Content-Type: application/json

{
  "nimetus": "prae muna",
  "prioriteet": 1, 
  "kasTehtud": true,
}

### Osaleja lisamine matkale
POST http://localhost:3030/api/matk/0/osaleja
Content-Type: application/json

{
    "email": "uus.matkaja4@test.ee"
}

### Osaleja eemaldamine matkalt
DELETE http://localhost:3030/api/matk/4343434/osaleja/0

